spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/kcoleman731/ssp-eks-workloads
    targetRevision: main
  ingress:
    host: kcaws.people.aws.dev