labels:
  env: prod
  team: geordie
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/aws-samples/eks-blueprints-workloads
    targetRevision: main